"""add family posts

Revision ID: 36f04e2b2ddd
Revises: d91e5953cf2f
Create Date: 2026-03-31 22:32:55.480538

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '36f04e2b2ddd'
down_revision = 'd91e5953cf2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('child_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('original_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_posts_child_name'), 'family_posts', ['child_name'], unique=False)
    op.create_index(op.f('ix_family_posts_original_id'), 'family_posts', ['original_id'], unique=True)
    op.create_index(op.f('ix_family_posts_post_date'), 'family_posts', ['post_date'], unique=False)
    op.create_index(op.f('ix_family_posts_source'), 'family_posts', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_posts_source'), table_name='family_posts')
    op.drop_index(op.f('ix_family_posts_post_date'), table_name='family_posts')
    op.drop_index(op.f('ix_family_posts_original_id'), table_name='family_posts')
    op.drop_index(op.f('ix_family_posts_child_name'), table_name='family_posts')
    op.drop_table('family_posts')
    # ### end Alembic commands ###
