"""Add current_task_info to agents

Revision ID: d91e5953cf2f
Revises: h1a2b3c4d5e6
Create Date: 2026-03-30 23:35:55.842234

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91e5953cf2f'
down_revision = 'h1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_events_event_type_created_at'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_task_comment_task_id_created_at'), table_name='activity_events', postgresql_where="((event_type)::text = 'task.comment'::text)")
    op.drop_constraint(op.f('fk_activity_events_board_id_boards'), 'activity_events', type_='foreignkey')
    op.create_foreign_key(None, 'activity_events', 'boards', ['board_id'], ['id'])
    op.add_column('agents', sa.Column('current_task_info', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_board_memory_board_id_is_chat_created_at'), table_name='board_memory')
    op.drop_constraint(op.f('uq_board_tcf_binding'), 'board_task_custom_fields', type_='unique')
    op.create_unique_constraint('uq_board_tcf_board_id_def_id', 'board_task_custom_fields', ['board_id', 'task_custom_field_definition_id'])
    op.drop_index(op.f('ix_board_webhook_payloads_board_webhook_received_at'), table_name='board_webhook_payloads')
    op.drop_constraint(op.f('gateway_installed_skills_gateway_id_fkey'), 'gateway_installed_skills', type_='foreignkey')
    op.create_foreign_key(None, 'gateway_installed_skills', 'gateways', ['gateway_id'], ['id'])
    op.drop_constraint(op.f('uq_tcf_def_org_key'), 'task_custom_field_definitions', type_='unique')
    op.create_unique_constraint('uq_task_custom_field_definitions_org_id_field_key', 'task_custom_field_definitions', ['organization_id', 'field_key'])
    op.drop_constraint(op.f('uq_tcf_values_task_def'), 'task_custom_field_values', type_='unique')
    op.create_unique_constraint('uq_task_cf_values_task_id_def_id', 'task_custom_field_values', ['task_id', 'task_custom_field_definition_id'])
    op.drop_index(op.f('ix_tasks_board_id_assigned_agent_id_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_board_id_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_board_id_status_created_at'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_board_id_status_created_at'), 'tasks', ['board_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_board_id_created_at'), 'tasks', ['board_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_board_id_assigned_agent_id_created_at'), 'tasks', ['board_id', 'assigned_agent_id', 'created_at'], unique=False)
    op.drop_constraint('uq_task_cf_values_task_id_def_id', 'task_custom_field_values', type_='unique')
    op.create_unique_constraint(op.f('uq_tcf_values_task_def'), 'task_custom_field_values', ['task_id', 'task_custom_field_definition_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_task_custom_field_definitions_org_id_field_key', 'task_custom_field_definitions', type_='unique')
    op.create_unique_constraint(op.f('uq_tcf_def_org_key'), 'task_custom_field_definitions', ['organization_id', 'field_key'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'gateway_installed_skills', type_='foreignkey')
    op.create_foreign_key(op.f('gateway_installed_skills_gateway_id_fkey'), 'gateway_installed_skills', 'gateways', ['gateway_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_board_webhook_payloads_board_webhook_received_at'), 'board_webhook_payloads', ['board_id', 'webhook_id', 'received_at'], unique=False)
    op.drop_constraint('uq_board_tcf_board_id_def_id', 'board_task_custom_fields', type_='unique')
    op.create_unique_constraint(op.f('uq_board_tcf_binding'), 'board_task_custom_fields', ['board_id', 'task_custom_field_definition_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_board_memory_board_id_is_chat_created_at'), 'board_memory', ['board_id', 'is_chat', 'created_at'], unique=False)
    op.drop_column('agents', 'current_task_info')
    op.drop_constraint(None, 'activity_events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_activity_events_board_id_boards'), 'activity_events', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_activity_events_task_comment_task_id_created_at'), 'activity_events', ['task_id', 'created_at'], unique=False, postgresql_where="((event_type)::text = 'task.comment'::text)")
    op.create_index(op.f('ix_activity_events_event_type_created_at'), 'activity_events', ['event_type', 'created_at'], unique=False)
    # ### end Alembic commands ###
