"""add channels and cronjobs to agent

Revision ID: g1c2d3e4f5a7
Revises: f1b2c3d4e5a6
Create Date: 2026-03-23 11:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'g1c2d3e4f5a7'
down_revision: Union[str, None] = 'f1b2c3d4e5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('channels_config', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('cronjobs_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'cronjobs_config')
    op.drop_column('agents', 'channels_config')
    # ### end Alembic commands ###
